---
kind: pipeline
type: docker
name: check_chia_og

steps:
- name: clone_chia_og
  image: alpine/git
  commands:
  - pwd
  - ls -al

- name: check
  image: kayuii/github-checker
  commands:
  - github-checker hpool-dev/chia-miner
  - URL=$(cat chia-og/version | github-checker hpool-dev/chia-miner)
  - XPROXY=$(echo "$URL" | grep xproxy)
  - HPOOL_LINUX=$(echo "$URL" | grep linux)
  - |
    if [ -n $XPROXY ]; then
      mkdir -p chia-og/tmp
      wget -qO ./chia-og/tmp/xproxy.zip $XPROXY
      wget -qO ./chia-og/tmp/linux.zip $HPOOL_LINUX
      github-checker hpool-dev/chia-miner | tee chia-og/version
    fi

- name: unzip
  image: alpine/git
  commands:
  - cd chia-og
  - unzip tmp/xproxy.zip -d "tmp"
  - unzip tmp/linux.zip -d "tmp"
  - export BUILD_TAG=$(cat chia-og/version | awk '{gsub(/\(|\)/,"");printf $2 "-" $3}')
  - ls -al

- name: publish
  image: thegeeklab/drone-docker-buildx
  privileged: true
  settings:
    platforms: "amd64,arm64,arm"
    dockerfile: chia-og/Dockerfile
    build_args: "FILE=chia-og/tmp/linux/*-amd64"
    repo: kayuii/hpool-miner
    context: chia-og
  when:
    event:
      exclude:
      - pull_request

# ---
# kind: pipeline
# type: docker
# name: default

# platform:
#   os: linux
#   arch: amd64

# trigger:
#   ref:
#   - refs/heads/master
#   - refs/tags/**

# steps:
# - name: env
#   image: docker:git
#   commands:
#   - |
#     if [ $CI_BUILD_EVENT = "tag" ]; then
#       export BUILD_TAG=$DRONE_TAG
#     else
#       git fetch --tags
#       export BUILD_TAG=$(git describe)
#     fi
#     export TAGPRE=$(echo "${BUILD_TAG}" | cut -c12-16)
#     export TAGHPOOL=$(echo "${BUILD_TAG}" | cut -c16-23)
#     export TAGHPOOL_PP=$(echo "${BUILD_TAG}" | cut -c16-23)
#   - echo $$BUILD_TAG
#   - echo $$TAGPRE
#   - echo $$TAGHPOOL
#   - echo $$TAGHPOOL_PP


# - name: backend
#   image: plugins/docker
#   settings:
#     repo: kayuii/hpool-miner
#     dockerfile: ./Dockerfile
#     username: kayuii
#     password:
#       from_secret: DOCKER_PWD
#     tags: dev
#   depends_on:
#   - env
#   when:
#     ref:
#     - refs/heads/master

# depends_on:
#   - checkrepo

# volumes:
# - name: dockersock
#   host:
#     path: /var/run/docker.sock
